apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: breakoutscan-api
spec:
  template:
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/breakoutscan-api
          env:
            - name: API_HOST
              value: "0.0.0.0"
            - name: API_PORT
              value: "8000"
          ports:
            - containerPort: 8000

